version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "goauth"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15r5ze62bjrgb"
s3_prefix = "goauth"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"

