AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auth
  
  Sample SAM Template for auth

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5 
    Runtime: go1.x
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:  
        db_host: mumbai.cjxqih7putd2.ap-south-1.rds.amazonaws.com
        db_user: postgres
        db_name: dms
        db_pass: Ks1Jq1Sa6aeqkh8uYIg1
        jwt_key: Ks1Jq1Sa6aeqkh8uYIg1

Resources:
  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt CustomAuthorizerFunction.Arn
        ApiKeyRequired: true

  CustomAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: controllers/authorizer
      Handler: authorizer
      Runtime: go1.x

  SignupFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: controllers/signup
      Handler: signup
      Runtime: go1.x
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties: 
            RestApiId: !Ref AuthApi
            Auth:
              Authorizer: 'NONE'
            Path: /signup
            Method: POST

  LoginFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: controllers/login
      Handler: login
      Runtime: go1.x
      Events:
        Login:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref AuthApi
            Auth:
              Authorizer: 'NONE'
            Path: /login
            Method: POST

  UserInfoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: controllers/userinfo
      Handler: userinfo
      Runtime: go1.x
      Events:
        UserInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /profile
            Method: GET
Outputs:
  # AuthApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AuthAPI:
    Description: "API Gateway endpoint URL for Prod environment for Auth"
    Value: !Sub "https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
